// Code generated by go generate; DO NOT EDIT.

package plana

const (
	Version              = "1.72.452186"
	defaultBundleVersion = "s8tloc7lo3"
	defaultGatewayURL    = "https://prod-gateway.bluearchiveyostar.com:5100/api/"
	defaultGameURL       = "https://prod-game.bluearchiveyostar.com:5000/api/"
)
