package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
)

func TestRunGeneratesDefaultsFromFirstLiveConnectionGroup(t *testing.T) {
	t.Parallel()

	var server *httptest.Server
	server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if got, want := r.Header.Get("User-Agent"), "go-plana-defaults-generator/1.0"; got != want {
			t.Errorf("User-Agent = %q, want %q", got, want)
		}

		switch r.URL.Path {
		case "/version.txt":
			if _, err := io.WriteString(w, "1.71.449178\n"); err != nil {
				t.Errorf("write version response: %v", err)
			}
		case "/decompiled/1.71.449178/GameMainConfig.json":
			writeJSON(t, w, map[string]any{
				"DefaultConnectionGroup": 2,
				"Language":               "Jp",
				"ServerInfoDataUrl":      server.URL + "/server-info.json",
				"SkipTutorial":           false,
			})
		case "/server-info.json":
			writeJSON(t, w, map[string]any{
				"ConnectionGroups": []map[string]any{
					connectionGroupFixture("old", false, "https://old-game.example/api/", "https://old-gateway.example/api/"),
					connectionGroupFixture("first", true, "https://game.example/api/", "https://gateway.example/api/"),
					connectionGroupFixture("second", true, "https://second-game.example/api/", "https://second-gateway.example/api/"),
				},
			})
		default:
			http.NotFound(w, r)
		}
	}))
	t.Cleanup(server.Close)

	outputPath := filepath.Join(t.TempDir(), "defaults_generated.go")
	g := generator{
		client:          server.Client(),
		versionURL:      server.URL + "/version.txt",
		configURLFormat: server.URL + "/decompiled/%s/GameMainConfig.json",
		outputPath:      outputPath,
	}

	got, err := g.run(t.Context())
	if err != nil {
		t.Fatalf("generator.run() error = %v, want nil", err)
	}
	want := defaults{
		Version:       "1.71.449178",
		BundleVersion: "first",
		GatewayURL:    "https://gateway.example/api/",
		GameURL:       "https://game.example/api/",
	}
	if got != want {
		t.Errorf("generator.run() = %+v, want %+v", got, want)
	}

	generated, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) error = %v, want nil", outputPath, err)
	}
	wantGenerated := `// Code generated by go generate; DO NOT EDIT.

package plana

const (
	Version              = "1.71.449178"
	defaultBundleVersion = "first"
	defaultGatewayURL    = "https://gateway.example/api/"
	defaultGameURL       = "https://game.example/api/"
)
`
	if string(generated) != wantGenerated {
		t.Errorf("generated defaults =\n%s\nwant:\n%s", generated, wantGenerated)
	}
}

func connectionGroupFixture(bundleVersion string, isLivePublished bool, gameURL, gatewayURL string) map[string]any {
	return map[string]any{
		"Name":                       "Prod-Audit",
		"ManagementDataUrl":          "https://notice.example/index.json",
		"IsProductionAddressables":   true,
		"ApiUrl":                     gameURL,
		"GatewayUrl":                 gatewayURL,
		"KibanaLogUrl":               "https://logs.example",
		"ProhibitedWordBlackListUri": "https://notice.example/blacklist.csv",
		"ProhibitedWordWhiteListUri": "https://notice.example/whitelist.csv",
		"CustomerServiceUrl":         "https://support.example",
		"OverrideConnectionGroups":   []any{},
		"BundleVersion":              bundleVersion,
		"IsLivePublished":            isLivePublished,
	}
}

func writeJSON(t *testing.T, w http.ResponseWriter, value any) {
	t.Helper()
	if err := json.NewEncoder(w).Encode(value); err != nil {
		t.Errorf("json.Encode(%T) error = %v, want nil", value, err)
	}
}
